# 启动端口
server:
  port: 8800

# 日志配置文件
logging:
  config: classpath:log4j2-spring-${spring.profiles.active}.xml

spring:
  activiti: # activiti工作流配置
    database-schema-update: false # 是否自动更新数据库结构
    process-definition-location-prefix: classpath:/processes/ # 流程定义文件存放目录
    check-process-definitions: false # 是否自动检查、部署流程定义文件
    async-executor-activate: false # 是否开启Job executor activation
  datasource: # 数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activiti?characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: hello mysql

