# 启动端口
server:
  port: 8800

# 日志配置文件
logging:
  config: classpath:log4j2-spring-${spring.profiles.active}.xml

# activiti工作流配置
spring:
  activiti:
    database-schema-update: true #自动更新数据库结构
    process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录
    check-process-definitions: true #自动检查、部署流程定义文件
